BEGIN;

ALTER TABLE scam_pattern_examples
    ADD COLUMN IF NOT EXISTS embedding vector(768);

ALTER TABLE scam_pattern_examples
    DROP CONSTRAINT IF EXISTS scam_pattern_examples_embedding_metadata_consistent;

ALTER TABLE scam_pattern_examples
    ADD CONSTRAINT scam_pattern_examples_embedding_metadata_consistent CHECK (
        (
            embedding IS NULL
            AND embedding_model IS NULL
            AND embedding_dimensions IS NULL
        )
        OR
        (
            embedding IS NOT NULL
            AND embedding_model = 'gemini-embedding-2'
            AND embedding_dimensions = 768
            AND vector_dims(embedding) = 768
        )
    );

COMMENT ON COLUMN scam_pattern_examples.embedding IS
    'Curated example embedding generated by gemini-embedding-2 at 768 dimensions; never populated from runtime user input.';

COMMENT ON COLUMN scam_pattern_examples.embedding_model IS
    'Server-controlled embedding model identifier; Phase 5D-C requires gemini-embedding-2 when embedding is present.';

COMMENT ON COLUMN scam_pattern_examples.embedding_dimensions IS
    'Server-controlled vector dimension; Phase 5D-C requires 768 when embedding is present.';

COMMIT;
